steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh student-01-9d11674cd800@rachhu --zone=us-east1-c --command='
          mkdir -p /home/student-01-9d11674cd800/app;
          cd /home/student-01-9d11674cd800/app;
          if [ ! -d .git ]; then
            git clone https://github.com/Rachanack2003/python-vm-deploy.git .;
          else
            git pull;
          fi;
          chmod +x start.sh;
          ./start.sh
        '

timeout: 900s

options:
  logging: CLOUD_LOGGING_ONLY
